eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8085
spring:
  application:
    name: zuul
zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: ribbon
    feign:
      path: /feign/**
      serviceId: feign